# Generated by Django 5.1.3 on 2024-12-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='receta',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
