# Generated by Django 5.1.3 on 2024-12-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
