# Generated by Django 5.1.3 on 2024-12-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recetas', '0004_delete_ingrediente_delete_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la receta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('instrucciones', models.TextField(verbose_name='Instrucciones')),
                ('tiempo_preparacion', models.PositiveIntegerField(verbose_name='Tiempo de preparación (minutos)')),
                ('nivel_dificultad', models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], max_length=50, verbose_name='Nivel de dificultad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/', verbose_name='Imagen de la receta')),
                ('es_favorita', models.BooleanField(default=False, verbose_name='Es favorita')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
